#!/bin/sh

CHAIN=$1

if [ -z "$CHAIN" ] || [ "$CHAIN" = "--help" ]; then
    echo "Get a blacklist by a specified chain."
    echo ""
    echo "Usage:"
    echo "  print_blacklist <CHAIN>"
    echo ""
    echo "Example:"
    echo "  print_blacklist DOCKER"
    exit 1
fi

echo "Print blacklist from chain $CHAIN"
iptables -L "$CHAIN" | grep DROP | awk '{print $4}'
exit 0
